export const ERROR_CODES = {
  INVALID_BODY: "INVALID_BODY",
  NOT_FOUND: "NOT_FOUND",
  STARTS_AT_MUST_BE_FUTURE: "STARTS_AT_MUST_BE_FUTURE",
  HAS_APPOINTMENTS: "HAS_APPOINTMENTS",
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
